name: PHPStan_test
on: [push]
jobs:
  phpstantest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'
          tools: phpstan
      - name: Run PHPStan
        run: phpstan analyze --memory-limit=-1